services:
  app2:
    image: backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3011:3011
    container_name: container-backend-dev
    environment:
      - PORT=3011 #MIKSI TÄMÄ PITÄÄ MÄÄRRITTÄÄ BACKENDISSÄ MUTTA EI ESIMERKIN FRONTISSA??????
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      #Saisiko tänmän suoraan .envistä? En tiedä - en halua selvittää - kopioidaan.
      # - ARVO=image_nimi://tietokanta:portti
      # Portti määritetään erikseen kahteen kertaan koska se toimii "ovena" mongolle ja redikselle????
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db   #BIND MOUNT --> pitäisi pitää data tallessa..
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
  debug-helper:
    image: busybox

volumes:
  mongo_data:
  redis_data: